json_files: [dataset_context/new_c.json]

results_csv_name: "meancache-contextual-results.csv"

judge_llm: "llama3"

download_models: 0

all_models: None

check_cache: 1

cossim_t: 0.5
top_k: 5

# "Salesforce/SFR-Embedding-2_R"
# paraphrase-albert-small-v2
# 'all-mpnet-base-v2'
embedding_model_name: all-mpnet-base-v2 
